# Generated by Django 4.0.6 on 2022-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('mobile', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
