# Generated by Django 4.0.6 on 2022-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('post', models.CharField(choices=[('senior', 'senior'), ('junior', 'junior')], max_length=70)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
